### ISSUE TITLE
Reconnecting to DB in case of #2006 (Server has gone away)

### ISSUE THREAD

**Issue by MarcinOrlowski** [Webador/SlmQueueDoctrine#180]
I am facing a problem with Doctrine based SLM queues where I am loosing the connection to the DB. This is caused triggered by the server and I am not yet sure why this occurs (but let's ignore that for now). The problem is that when this occur, the client is still unaware of that fact (`isConnect()` returns true) unless it attempts to use the connection which then causes the whole worker to die because of unhandled `DBALException\ConnectionLost` exception.

I wonder if there's any reason to not attempt to reconnect automatically (that is sufficient to be done in `purge()` and `pop()`). The PDO does not implement `mysql_ping()` so any attempt to detect the real state of the connection seems tricky and basically i failed to find anything besides doing the query. And if so, I am willing to do the real query (not dummy `SELECT 1` or so) and just retry in case of failures.  I am going to implement that behavior but I'd like to hear you comments on that too. Thanks

**Comment by roelvanduijnhoven** [comment]
@MarcinOrlowski If the worker is doing nothing for a long time, that _could_ cause a timeout on the database, if not correctly configured. And indeed, Doctrine does not auto reconnect.

A tip: why not simply spend time instead in making sure the worker will restart after a crash? That's something that you will need to have anyway to get any sort of reliable job system working.

Anyhow: closing, as I don't think this should be in this library, because re-connecting is kinda of not meant to be done in Doctrine AFAIK.

**Comment by basz** [comment]
I attempted to create a lib that did this. But it was never a succes and in the end my disconnects went away.

I agree. Fix the disconnect not the symptom.


https://github.com/bushbaby/BsbDoctrineReconnect
